server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的过程，利用微服务名进行路由
      routes:
        - id: payment_routh   #路由id，没有固定规则，要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**  #断言 ，路径相匹配的进行路由
            #- After=2021-04-08T15:12:03.166+08:00[Asia/Shanghai]

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            #- After=2021-04-08T14:12:03.166+08:00[Asia/Shanghai] # 之后生效 Before Between
            #- Cookie=username, xyy # cookie中username必须等于xyy（通过cmd窗口可以模拟cookie#curl http://localhost:9527/payment/lb --cookie "username=xyy"）
            #- Header=X-Request-Id, \d+ #请求头包含X-Request-Id的属性并且值为整数（curl http://localhost:9527/payment/lb -H "X-Request-Id:124"）
            #- Method=GET,POST #
            #- Query=green #参数中包含green（curl http://localhost:9527/payment/lb?green=1）
          filters:
            - AddRequestHeader=X-Request-red, blue

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka