server:
  port: 7002
#eureka:
    #instance:
  #hostname: localhost
    #client:
    #不向注册中心注册自己
    # register-with-eureka: false
    #flase表示自己就是注册中心
    #fetch-registry: false
    #service-url:
    #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/



eureka:
  instance:
    hostname: eureka7002.com
  client:
    #不向注册中心注册自己
    register-with-eureka: false
    #flase表示自己就是注册中心
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
