server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiangyuyi-ambition/sprinfcloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
           - springcloud-config
      ####读取分支
      label: main

    #1.http://config-3344.com:3344/main/application-dev.yml
    #2.http://config-3344.com:3344/config/dev/main

#rabbitmq相关配置 15672是web管理界面的端口 5672是MQ访问的端口
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

