server:
  port: 80

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #将自己注册到eureka server
      register-with-eureka: false

ribbon:
  #建立连接后从服务器读取可用资源的时间
  ReadTimeout: 5000
  #建立连接时间
  ConnectTimeout: 5000

logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug
