server:
  port: 7001

#单机版
  #eureka:
    #instance:
  # hostname: localhost
    #client:
    #不向注册中心注册自己
    # register-with-eureka: false
    #flase表示自己就是注册中心
    #fetch-registry: false
    #service-url:
    #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#集群版
eureka:
  instance:
    hostname: eureka7001.com
  client:
    #不向注册中心注册自己
    register-with-eureka: false
    #flase表示自己就是注册中心
    fetch-registry: false
    service-url:
      #单机指向自己
      defaultZone: http://eureka7001.com:7001/eureka/
      #集群指向其他
      #defaultZone: http://eureka7002.com:7002/eureka/
  server:
    #关闭自我保护机制（不可用服务被剔除）
    enable-self-preservation: false
    #剔除时间
    eviction-interval-timer-in-ms: 2000
