server:
  port: 80

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
      #将自己注册到eureka server
      register-with-eureka: false

feign:
  hystrix:
    enabled: true
